name: Sync GitLab to GitHub

on:
  push:
    branches:
      - '*'  # 适用于所有分支

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitLab repository
        uses: actions/checkout@v3

      - name: Set up GitHub repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 从 Secrets 获取 GitHub Token
          GITHUB_GROUP: ${{ vars.GITHUB_GROUP }}    # 从环境变量获取 GitHub Group
          GITHUB_REPO: ${{ vars.GITHUB_REPO }}      # 从环境变量获取 GitHub Repo
        run: |
          # 获取当前 GitLab 分支名
          GITLAB_BRANCH=$(echo ${CI_COMMIT_REF_NAME} | sed 's/refs\/heads\///')

          # 设置 GitHub 仓库的远程 URL
          GITHUB_URL="https://${GITHUB_TOKEN}@github.com/${GITHUB_GROUP}/${GITHUB_REPO}.git"

          # 添加 GitHub 作为新的 remote
          git remote add github $GITHUB_URL

          # 確保倉庫完整克隆，避免 `--unshallow` 錯誤
          if [ -f .git/shallow ]; then git fetch --unshallow; fi

          # 推送当前分支到 GitLab
          git push --set-upstream github $GITLAB_BRANCH  # 将当前分支推送到 GitLab 仓库

      - name: Verify GitHub Push
        run: |
          git remote -v  # 显示 GitHub 仓库信息