stages:
  - sync

sync_to_github:
  stage: sync
  image: alpine:latest  # 使用 Alpine 輕量環境
  before_script:
    - apk add --no-cache git  # 安裝 git
  script:
    - echo "sync GitLab to GitHub"
    - echo "GitHub Group=${GITHUB_GROUP}"
    - echo "GitHub Repository=${GITHUB_REPO}"
    - echo "GitHub Token=${GITHUB_TOKEN}"
    
    # 設定 GitHub Token 和 遠端倉庫 URL
    - export GITHUB_URL="https://${GITHUB_TOKEN}@github.com/${GITHUB_GROUP}/${GITHUB_REPO}.git"

    # 檢出當前分支
    - git checkout ${CI_COMMIT_REF_NAME}

    # 設定 GitHub 遠端倉庫
    - git remote add github $GITHUB_URL

    # 確保倉庫完整克隆，避免 `--unshallow` 錯誤
    - if [ -f .git/shallow ]; then git fetch --unshallow; fi

    # 推送到 GitHub
    - git push --set-upstream github ${CI_COMMIT_REF_NAME}

  only:
    - branches  # 只在有推送分支時觸發